---
lax-edg-r1:
  hostname: '10.32.1.201'
  port: 22
  username: 'cisco'
  password: 'cisco'
  platform: 'cisco_ios'

lax-edg-r2:
  hostname: '10.32.1.202'
  port: 22
  username: 'cisco'
  password: 'cisco'
  platform: 'cisco_ios'
